---
- name: create postgresql database
  postgresql_db: name={{ item }}
                 owner={{ item }}
                 encoding='UTF-8'
                 lc_collate='ru_RU.UTF-8'
                 lc_ctype='ru_RU.UTF-8'
                 template='template0'
  become_user: postgres
  with_items:
    - app
